# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8eb716e6a023a85e4ce6af02a26c7544deea142c176b4f6cb5b556db0d3de228b96f6bdf9a8022bcdcbe4f23de67812ca78abfb908b79ce5a4e32c6db90abc7

test:
  secret_key_base: 0febba2a2fe38cb6e367077b8ed2632e0da23d9177443c33b9ea687fac550f1954d281603931b3a9660aa5fd4e608cb87b22819632bfa930c254084b55db03ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
